name: IPFS

on:
  push:
    branches: ["next"]
  workflow_dispatch:

jobs:
  deploy-ipfs:
    runs-on: ${{ matrix.os }}
    if: "!(startsWith(github.event.head_commit.message, 'badge:'))"

    strategy:
      fail-fast: false
      matrix:
        node-version: ['16.x']
        os: ['ubuntu-latest']

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install project dependencies
        run: yarn --prefer-offline
        id: install

      - run: yarn export

      - name: Upload to IPFS
        uses: aquiladev/ipfs-action@v0.3.0-alpha.1
        id: ipfs
        with:
          path: './ipfs/'
          host: ${{ secrets.IPFS_HOST }}
          port: ${{ secrets.IPFS_PORT }}
          protocol: http

      - uses: emibcn/badge-action@v1.2.1
        with:
          label: 'IPFS'
          status: ${{ steps.ipfs.outputs.hash }}
          color: '#0657F9'
          path: '.github/badges/ipfs.svg'

      - name: Upload badge as artifact
        uses: actions/upload-artifact@v3
        with:
          name: badge
          path: '.github/badges/ipfs.svg'
          if-no-files-found: error

      - name: Commit badge
        continue-on-error: true
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add '.github/badges/ipfs.svg'
          git commit -m "badge: update IPFS link"

      - name: Push badge commit
        uses: ad-m/github-push-action@master
        if: ${{ success() }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'main'







