name: IPFS

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy-ipfs:
    runs-on: ${{ matrix.os }}
    if: "!(startsWith(github.event.head_commit.message, 'badge:'))"

    strategy:
      fail-fast: false
      matrix:
        node-version: ['16.x']
        os: ['ubuntu-latest']

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install project dependencies
        run: yarn --prefer-offline
        id: install

      - run: yarn export

      - name: Upload to IPFS
        uses: aquiladev/ipfs-action@v0.3.0-alpha.1
        id: ipfs
        with:
          path: './ipfs/'
          host: ${{ secrets.IPFS_HOST }}
          port: ${{ secrets.IPFS_PORT }}
          protocol: http

      - uses: emibcn/badge-action@v1.2.1
        with:
          label: 'IPFS'
          status: ${{ steps.ipfs.outputs.hash }}
          color: '#0657F9'
          path: '.github/badges/ipfs.svg'

      - name: Create Release
        uses: Hs1r1us/Release-AIO@v1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.ipfs.outputs.hash }}
          release_name: 'IPFS ${{ steps.ipfs.outputs.hash }}'
          body: 'ipfs://${{ steps.ipfs.outputs.hash }}) - [ipfs.io](https://ipfs.io/ipfs/${{ steps.ipfs.outputs.hash }})'





